### ISSUE TITLE
Question: what error status does the API raise?

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-storage#119]
According to #100, the server may raise 403. However, there is no documentation about what errors they can raise.
- For example, currently large sounds raise 503. However, it should raise 413, or at least 400 with some custom results.
- Does it raise 401 for invalid session?
- Same for 415 (for invalid asset)

**Comment by rschamp** [comment]
We don't currently intend our APIs to be used for anything other than the Scratch website, so we don't provide documentation for them. But we do try to use a status code that best matches the situation as closely as possible with a few exceptions.

I think that 503 response is a bug because we aren't handling the upload well enough to return the 413 before the edge server times out the request (503). We try to return a 413 in this situation though.

Sometimes we opt to not distinguish between unauthorized vs forbidden vs not found requests and just always return one of 403 or 404. This is to reduce the amount of information we're conveying if it's unnecessary for our application to distinguish between these states.
