### ISSUE TITLE
PR to load assets in a web worker not accepted because storage is issuing puts on the asset server

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-storage#88]
@picklesrus discovered in the bug hunt that Scratch is issuing puts to update assets on the asset server when it should be using Posts.  

We shouldn't ever try to update the md5 hash because they are unique and changing the image should have a new md5 hash.  

The server doesn't accept puts, anyway and was sending back 405 errors while saving assets.

This came from testing https://github.com/LLK/scratch-gui/pull/4726, which we reverted on develop.

**Comment by picklesrus** [comment]
I was just playing around in the paint editor when it happened. I was editing costumes (and therefore creating new assets) but I'm not sure whether it happened when the asset was created or when the periodic project save kicked in. @paulkaplan saw it too so might have more prescriptive repro steps.

**Comment by mzgoddard** [comment]
Ah. So GUI is overwriting the http method through the request configuration for the asset url method in the web store.

I guess this is an undocumented way of using storage to force a http method since storage's way of deciding between post and put requests doesn't support the use case of already having an asset id.

I'll have a change to fix this soon.
